### ISSUE TITLE
Build failure on ubuntu 16.04 with gcc 5.4

### ISSUE THREAD

**Issue by ekg** [StanfordPL/stoke#949] opened 2017-03-31 15:37 UTC
`bin/stoke` seems to have been built, but I'm getting an error in `make release`, which I guess is run by default when running `make`.

I'm on ubuntu 16.04, with gcc 5.4:

```
-> % gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
```

Here's the build error:

```
In file included from ../../../source/include/pin/pin.H:41:0,
                 from testcase.cpp:33:
../../../source/include/pin/compiler_version_check2.H:102:2: error: #error The C++ ABI of your compiler does not match the ABI of the pin kit.
 #error The C++ ABI of your compiler does not match the ABI of the pin kit.
  ^
../../../source/include/pin/compiler_version_check2.H:117:2: error: #error This kit requires gcc 3.4 or later
 #error This kit requires gcc 3.4 or later
  ^
Makefile:77: recipe for target 'obj-intel64/testcase.o' failed
make[2]: *** [obj-intel64/testcase.o] Error 1
make[2]: Leaving directory '/home/erik/stoke/src/ext/pin-2.13-62732-gcc.4.4.7-linux/source/tools/stoke'
Makefile:327: recipe for target 'pintool' failed
make[1]: *** [pintool] Error 2
make[1]: Leaving directory '/home/erik/stoke'
Makefile:256: recipe for target 'release' failed
make: *** [release] Error 2
```

**Comment by stefanheule** [comment] 2017-09-11 20:32
Closing this as a duplicate of https://github.com/StanfordPL/stoke/issues/887

**Closed as completed by stefanheule** 2017-09-11 20:32 UTC
