### ISSUE TITLE
Validation fails on sequences involve shift operations

### ISSUE THREAD

**Issue by thisismiller** [StanfordPL/stoke#973] opened 2017-08-11 07:17 UTC
I'm attempting to throw the following asm snippet at stoke, to see if it comes up with some clever way to get rid of the bswaps.

```
.dbl:
  movq 0x8(%rdi), %rcx    #  1     0x400690  4      OPC=movq_r64_m64        
  movq (%rdi), %rsi       #  2     0x400694  3      OPC=movq_r64_m64        
  bswap %rcx              #  3     0x400697  3      OPC=bswap_r64           
  bswap %rsi              #  4     0x40069a  3      OPC=bswap_r64           
  movq %rcx, %r10         #  5     0x40069d  3      OPC=movq_r64_r64        
  movq %rsi, %rax         #  6     0x4006a0  3      OPC=movq_r64_r64        
  movq %rsi, %r9          #  7     0x4006a3  3      OPC=movq_r64_r64        
  shldq $0x1, %rsi, %r10  #  8     0x4006a6  5      OPC=shldq_r64_r64_imm8  
  addq %rsi, %r9          #  9     0x4006ab  3      OPC=addq_r64_r64        
  andl $0x87, %eax        #  10    0x4006ae  5      OPC=andl_eax_imm32      
  xorq %r9, %rax          #  11    0x4006b3  3      OPC=xorq_r64_r64        
  movq %r10, %rdx         #  12    0x4006b6  3      OPC=movq_r64_r64        
  bswap %rdx              #  13    0x4006b9  3      OPC=bswap_r64           
  bswap %rax              #  14    0x4006bc  3      OPC=bswap_r64           
  movq %rax, (%rdi)       #  15    0x4006bf  3      OPC=movq_m64_r64        
  movq %rdx, 0x8(%rdi)    #  16    0x4006c2  4      OPC=movq_m64_r64        
  retq                    #  17    0x4006c6  1      OPC=retq                
```
(C file that I used for stoke is at https://gist.github.com/thisismiller/717ef49ae33c26df89b47af2e25ffe43 if you want to play with this yourself.)

This sequence fails validation
FATAL ERROR: (dbl) Reads from an undefined location: Instruction 'movq %r10, %rdx' reads { %r10 } but only { %rax %rcx %rbx %rsp %rbp %rsi %rdi %r9 %r12 %r13 %r14 %r15 %xmm0 %xmm1 %cf %pf %zf %sf %of %mxcsr::rc[0] } are defined.

It sees %r10 as undefined because it's the result of shldq, which in x64asm, SHLD and friends are marked as Rwu, so their result is undefined.  The result is conditionally undefined, if the shift amount is larger than the argument size, and there's no way to encode this conditional-undefined-ness.

I've removed the u attribute locally, and everything seems to have gone fine.  (Well, by fine, I mean I then hit crashes from invalid REPNZ prefixes which appears to be bug #840 as I am on a skylake.)  But I have no idea what "proper" fix to recommend.

**Comment by stefanheule** [comment] 2017-08-11 07:21
Yeah, unfortunately with the current dataflow analysis, STOKE is not able to use the shld instruction, because the output might always be undefined and so can't be used.  Probably just changing it locally to make it defined will work just fine, though STOKE might rely on the output even when it is technically undefined.  If you can live with that, go for it.

There is no easy solution, unfortunately.

**Comment by thisismiller** [comment] 2017-08-12 03:29
Is the only downside that I should manually prove/verify afterwards that the result of the shift instruction will always be defined, or is there something else that would confuse STOKE internally?

**Comment by stefanheule** [comment] 2017-08-13 05:04
That's the main downside, correct.  If you run on a CPU that has non-deterministic behavior for the undefined case, that would be an issue for STOKE, I think, but I don't think such CPUs exist.  They all choose some deterministic (but unspecified according to the Intel manual) behavior.

**Comment by bchurchill** [comment] 2017-09-02 03:14
There is a ready-made solution to this problem in the validator, although not the search.  If you use "stoke debug verify", you can provide the --live_dangerously option, and it will ignore the results of the analysis.  (Or at least that's the intended behavior -- let us know if it doesn't work).  The search however always checks the results of the analysis to avoid undefined behavior in the sandbox and we don't have a meaningful solution to this problem at the moment.

However, I was going to recommend exactly what you did -- just remove the "u" from the x64asm spreadsheet.  I'll close this issue for now but feel free to reopen if needed.

**Closed as completed by bchurchill** 2017-09-02 03:14 UTC
