### ISSUE TITLE
Stoke produce incorrect rewrite for global variable

### ISSUE THREAD

**Issue by yzhao30** [StanfordPL/stoke#970] opened 2017-07-20 07:32 UTC
It can be reproduced using the example tutorial, just add a global variable

```C++
uint64_t ga = 0;
size_t popcnt(uint64_t x) {
  int res = 0;
  for (; x > 0; x >>= 1) {
    res += x & 0x1ull;
  }
  ga += res;
  return res;
}
```

The original function is

```asm
  # Text                       #  Line  RIP       Bytes  Opcode             
._Z6popcntm:                 #        0x4006d0  0      OPC=<label>        
  testq %rdi, %rdi           #  1     0x4006d0  3      OPC=testq_r64_r64  
  je .L_4006f6               #  2     0x4006d3  2      OPC=je_label       
  xorl %eax, %eax            #  3     0x4006d5  2      OPC=xorl_r32_r32           
.L_4006e0:                   #        0x4006e0  0      OPC=<label>        
  movl %edi, %edx            #  13    0x4006e0  2      OPC=movl_r32_r32   
  andl $0x1, %edx            #  14    0x4006e2  3      OPC=andl_r32_imm8  
  addl %edx, %eax            #  15    0x4006e5  2      OPC=addl_r32_r32   
  shrq $0x1, %rdi            #  16    0x4006e7  3      OPC=shrq_r64_one   
  jne .L_4006e0              #  17    0x4006ea  2      OPC=jne_label      
  cltq                       #  18    0x4006ec  2      OPC=cltq           
.L_4006ee:                   #        0x4006ee  0      OPC=<label>        
  addq %rax, 0x200953(%rip)  #  19    0x4006ee  7      OPC=addq_m64_r64   
  retq                       #  20    0x4006f5  1      OPC=retq           
.L_4006f6:                   #        0x4006f6  0      OPC=<label>        
  xorl %eax, %eax            #  21    0x4006f6  2      OPC=xorl_r32_r32   
  jmpq .L_4006ee             #  22    0x4006f8  2      OPC=jmpq_label     
```

the rewrite is

```asm
._Z6popcntm:         #        0x4006d0  0      OPC=<label>          
  popcntq %rdi, %r9  #  1     0x4006d0  5      OPC=popcntq_r64_r64  
  xchgq %r9, %rax    #  2     0x4006d5  3      OPC=xchgq_r64_r64_1  
  retq               #  3     0x4006d8  1      OPC=retq           
``` 

The optimization totally ignore the global variable. Besides, instruction with memory dereference also results in incorrect rewrite. I am not sure how does the STOKE generate testcases for memory locations.

**Comment by stefanheule** [comment] 2017-07-20 15:36
Can you give the full code of how you invoke STOKE? Otherwise it's
impossible to reproduce.

Are you using --stack_out and --heap_out?

**Comment by yzhao30** [comment] 2017-07-20 19:54
I just modify the `stoke/example/tutorial/main.cc` and run `make`. I forgot to add the `--stack_out` and `--heap_out` in the example. But after I added them, the rewrite becomes:

```asm
._Z6popcntm:                 #        0x4006d0  0      OPC=<label>          ¬
  popcntq %rdi, %rax         #  1     0x4006d0  5      OPC=popcntq_r64_r64  ¬
  addl %eax, 0x20096d(%rip)  #  2     0x4006d5  6      OPC=addl_m32_r32     ¬
  retq                       #  3     0x4006db  1      OPC=retq             ¬
```
The Stoke capture the global variable now but the address `0x20096d` is different than the original `0x200953`, can you confirm this? Thanks.

**Comment by stefanheule** [comment] 2017-07-20 20:23
`0x20096d` is not the address, but just the offset from `%rip`.  Since the instruction moved to a different address, `%rip` will be different, and it looks to me that this is working as intended.  Have you tried running the rewrite?  Is it working?

**Comment by bchurchill** [comment] 2017-07-20 21:19
I agree with Stefan that it looks correct.  But if it doesn't work, try
using "--strategy bounded" if you're not already.  It should handle RIP
offsets and global variables correctly as long as memory is marked as live
out.  It will rerun the search until it finds something that's correct for
all short executions of the program.


On Jul 20, 2017 13:23, "Stefan Heule" <notifications@github.com> wrote:

0x20096d is not the address, but just the offset from %rip. Since the
instruction moved to a different address, %rip will be different, and it
looks to me that this is working as intended. Have you tried running the
rewrite? Is it working?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/StanfordPL/stoke/issues/970#issuecomment-316819252>,
or mute
the thread

**Comment by yzhao30** [comment] 2017-07-20 21:43
I see. Yes it seems the rewrite is correct after using the --stack_out and --heap_out. I use the tutorial example to reproduce this issue because I met this error in other programs, but I will check the options first. I will close this issue after the conversation. 

By the way, in the `hold_out` strategy, does stoke also run the formal validation in the end or it only runs the `testcase` verification and not the formal validator at all? In my observation, the successful found rewrite in the `bold_out` also fail the program very likely. Thanks.

**Comment by stefanheule** [comment] 2017-07-20 21:45
hold_out only runs the testcases, so how well the rewrite works depends 
a lot on how good the testcases are.  bounded and ddec are the two 
strategies that use a formal validator.

**Comment by yzhao30** [comment] 2017-07-21 00:11
Thanks. I use the autogen mode to generate the testcases, so I guess I need to try the other strategies.

**Closed as completed** 2017-07-21 00:11 UTC

**Comment by stefanheule** [comment] 2017-07-21 00:13
Yeah, autogen just generates random test-cases, which may or may not give you great coverage.  The easiest way to get better testcases is often to write a test harness in C, and then use `stoke testcase` to automatically record testcases from the harness.  This way, you have full control over what the test inputs look like.
