### ISSUE TITLE
FATAL ERROR: Target/rewrite requires unavailable cpu flags: { avx } on nehalem

### ISSUE THREAD

**Issue by falk-hueffner** [StanfordPL/stoke#838] opened 2016-02-11 20:56 UTC
My machine doesn't have AVX. `./configure.sh` correctly writes `STOKE_PLATFORM="nehalem"` into `.stoke_config`. When following the tutorial from `README.md`, everything works fine until 

```
$ stoke search --config search.conf
WARNING: Some cpu flags are not available on this hardware and will be removed:
WARNING: { syscall rdtscp pclmulqdq fma movbe aes xsave avx f16c rdrand lahf_lm abm xsaveopt fsgsbase bmi1 hle avx2 bmi2 erms invpcid rtm }
FATAL ERROR: Target/rewrite requires unavailable cpu flags: { avx }

```

**Comment by stefanheule** [comment] 2016-02-11 22:00
Thanks for the report, I can reproduce this.  @bchurchill, this seems to be a duplicate of https://github.com/StanfordPL/stoke/issues/754, do you know why this didn't get fixed there, and also why our build doesn't catch this?

**Comment by bchurchill** [comment] 2016-02-11 22:37
The best thing you can do is to move to a sandybridge or haswell system (haswell is preferred), because right now we don't have the capacity to offer timely bug-fixes for Nehalem.

We didn't catch this because we only test on haswell and sandybridge.  There could be many nehalem bugs.  It's possible that it's a duplicate of #754, but it might not be.  It could be something besides init zero that's broken.  If indeed init zero is broken, it's almost definitely because of the VXORPD_YMM_YMM_YMM instruction, which isn't available on nehalem.  However, from a casual gander at the code, I don't see how this would be a problem if ymm registers are not live out.

**Comment by stefanheule** [comment] 2016-02-11 22:56
We used to run tests on nehalem, I guess you disabled that?

The way STOKE is written, we create zero programs for RegSet::all() (or whatever we call the full set), so ymm registers will be in there on every platform.

**Comment by bchurchill** [comment] 2016-02-11 22:58
No, we never have.  We used to compile STOKE for a nehalem build and run it on a haswell machine, but that's different.  It can catch some bugs, but not all bugs.  For example, if STOKE proposes an AVX instruction in the nehalem-build-running-on-haswell, everything will be fine; but on a real nehalem-build-running-on-nehalm it will segfault.  We still do this "fake" testing on the sandybridge jenkins running on lofty.

**Comment by stefanheule** [comment] 2016-02-11 23:00
Yes, but this is a bug that would be caught by running a nehalem build on a sandybridge or haswell machine.  I reproduced this bug on sandybridge just a minute ago, so clearly no nehalem machine required.

**Comment by bchurchill** [comment] 2016-02-11 23:02
Well, one true caveat is that we don't have github setup to trigger builds for the sandybridge setup, so we have to do that manually.  You're welcome to investigate why that setup isn't doing its job.  Either way, I don't think we can offer reliable support for nehalem right now.

**Comment by stefanheule** [comment] 2016-02-11 23:02
Then let's use this ticket to issue an error in ./configure.sh on nehalem.

**Comment by bchurchill** [comment] 2016-02-11 23:04
Sounds good to me.

**Comment by bchurchill** [comment] 2016-02-12 00:05
In the mean time, @falk-hueffner, you might try commenting out all the contents of `flag_check()` around line 140 of tools/gadgets/cfg.h.

**Closed as completed** 2016-02-24 22:46 UTC
Labels: bug, low

**Comment by shrin18** [comment] 2019-04-19 11:01
Hello, 

stoke synthesize --config synthesize.conf
FATAL ERROR: Target/rewrite requires unavailable cpu flags: { avx }
stoke@88995c24d66d:~/stoke/examples/tutorial$ 

I am not able to run synthesize. Is this problem fixed ? I am experimenting with stoke as my Master Project.

Thanks.
Shrinish Donde.

**Comment by stefanheule** [comment] 2019-04-19 14:27
As you can see in the hardware [prerequisites section](https://github.com/StanfordPL/stoke#hardware-prerequisites), you appear to use a CPU that might not be fully supported.  You can try removing avx from the cpu flags, but it may not work even with that.

**Comment by shrin18** [comment] 2019-04-20 07:34
> As you can see in the hardware [prerequisites section](https://github.com/StanfordPL/stoke#hardware-prerequisites), you appear to use a CPU that might not be fully supported. You can try removing avx from the cpu flags, but it may not work even with that.

Oh I even tried to remove avx and put mmx which seems to be the flag similar to avx for nehalem. I fixed it in the ./confiugre.sh and it worked fine. I was able to run make. But this doesn't work. Actually I have a instance on one of the CLoud services and they use nehalem machine. So I don't have  a way out of that..

I am working with KTH as a Research Engineer to make improvements to the code.
I hope that you can help me on this matter. 
--Thanks, 
Shrinish Donde.
KTH, Stockholm
