### ISSUE TITLE
Dependency on libboost_regex

### ISSUE THREAD

**Issue by 0xDouze** [StanfordPL/stoke#915] opened 2016-06-28 14:58 UTC
Good afternoon,
there still are dependencies on boost_regex although I am compiling with GCC-4.9 and am on Ubuntu 16.04, which causes the project to not compile correctly.

**Comment by stefanheule** [comment] 2016-06-28 16:22
We are working on on support for the current Ubuntu release (see #887), but we have not finished that work yet.  I don't think using boost_regex should be a problem, at least it wasn't last time I worked on getting STOKE to build on Ubuntu 16.04.  I will close this ticket as a duplicate of #887.  Once that is fixed, building on Ubuntu 16.04 should work.

**Closed as completed by stefanheule** 2016-06-28 16:22 UTC
Labels: duplicate

**Comment by bchurchill** [comment] 2016-07-23 04:16
You can now checkout the ubuntu16.04 branch.  It will allow you to compile and run stoke using gcc-4.9.  It's missing some of the testing features on our main branch, and so it's probably not going to get merged into develop ever.  But, you can use it until we get proper support for gcc-5.3 working.
